Class {
	#name : #WBCanvasTests,
	#superclass : #TestCase,
	#category : #'SqueakWhiteboard-Tests'
}

{
	#category : #setUp,
	#'squeak_changestamp' : 'is 6/2/2024 00:44'
}
WBCanvasTests >> setUp [

]

{
	#category : #tearDown,
	#'squeak_changestamp' : 'is 6/2/2024 00:44'
}
WBCanvasTests >> tearDown [
]

{
	#category : #tests,
	#'squeak_changestamp' : 'is 6/2/2024 00:42'
}
WBCanvasTests >> testTest [

	self assert: 1 = 1
	
]
